environment: local

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/orders
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
